version: '3'

services:
  find-a-friend:
    image: bitnami/postgresql
    container_name: find-a-friend
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findafriend-p
    ports:
      - "5432:5432"
    restart: always
